# Generated by Django 4.2.16 on 2025-05-26 11:20

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('donations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='fooddonation',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='fooddonation',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='donations/'),
        ),
        migrations.AddField(
            model_name='fooddonation',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Reserved', 'Reserved'), ('Donated', 'Donated'), ('Expired', 'Expired')], default='Available', max_length=20),
        ),
        migrations.AddField(
            model_name='fooddonation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='fooddonation',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='donations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='foodwaste',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='foodwaste',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='waste/'),
        ),
        migrations.AddField(
            model_name='foodwaste',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='waste_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fooddonation',
            name='quantity',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.1)]),
        ),
        migrations.AlterField(
            model_name='fooddonation',
            name='type',
            field=models.CharField(choices=[('Fruit', 'Fruit'), ('Vegetable', 'Vegetable'), ('Meat', 'Meat'), ('Dairy', 'Dairy'), ('Bakery', 'Bakery'), ('Canned', 'Canned'), ('Other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='foodwaste',
            name='quantity',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.1)]),
        ),
        migrations.AlterField(
            model_name='foodwaste',
            name='reason',
            field=models.CharField(choices=[('Spoilage', 'Spoilage'), ('Overproduction', 'Overproduction'), ('Expired', 'Expired'), ('Damaged', 'Damaged'), ('Other', 'Other')], max_length=50),
        ),
        migrations.CreateModel(
            name='DonationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Completed', 'Completed')], default='Pending', max_length=20)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('donation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='donations.fooddonation')),
                ('donation_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donations.donationcenter')),
            ],
        ),
        migrations.AddField(
            model_name='fooddonation',
            name='donation_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='donations.donationcenter'),
        ),
    ]
